import os
import sys
import tarfile
import shutil

print("Building Linux AppDir and OptiCleaner.AppImage...")

linux_dir = os.path.abspath("Linux")
src_dir = os.path.abspath("src")
app_dir = os.path.join(linux_dir, "AppDir")

# Clean existing AppDir
if os.path.exists(app_dir):
    shutil.rmtree(app_dir)

os.makedirs(os.path.join(app_dir, "usr", "bin"), exist_ok=True)
os.makedirs(os.path.join(app_dir, "usr", "lib"), exist_ok=True)
os.makedirs(os.path.join(app_dir, "usr", "share", "opticleaner", "images"), exist_ok=True)
os.makedirs(os.path.join(app_dir, "usr", "share", "applications"), exist_ok=True)
os.makedirs(os.path.join(app_dir, "usr", "share", "icons", "hicolor", "256x256", "apps"), exist_ok=True)

# Copy files
shutil.copy2(os.path.join(src_dir, "app.py"), os.path.join(app_dir, "usr", "share", "opticleaner", "app.py"))
if os.path.exists(os.path.join(src_dir, "cyber_visuals.html")):
    shutil.copy2(os.path.join(src_dir, "cyber_visuals.html"), os.path.join(app_dir, "usr", "share", "opticleaner", "cyber_visuals.html"))

# Copy images
images_src = os.path.join(src_dir, "images")
if os.path.exists(images_src):
    for f in os.listdir(images_src):
        sp = os.path.join(images_src, f)
        if os.path.isfile(sp):
            shutil.copy2(sp, os.path.join(app_dir, "usr", "share", "opticleaner", "images", f))

# Copy desktop and icon
shutil.copy2(os.path.join(linux_dir, "opticleaner.desktop"), os.path.join(app_dir, "opticleaner.desktop"))
shutil.copy2(os.path.join(linux_dir, "opticleaner.desktop"), os.path.join(app_dir, "usr", "share", "applications", "opticleaner.desktop"))
shutil.copy2(os.path.join(linux_dir, "opticleaner.png"), os.path.join(app_dir, "opticleaner.png"))
shutil.copy2(os.path.join(linux_dir, "opticleaner.png"), os.path.join(app_dir, "usr", "share", "icons", "hicolor", "256x256", "apps", "opticleaner.png"))
shutil.copy2(os.path.join(linux_dir, "AppRun"), os.path.join(app_dir, "AppRun"))

# Create compressed payload
tar_path = os.path.join(linux_dir, "payload.tar.gz")
with tarfile.open(tar_path, "w:gz") as tar:
    tar.add(app_dir, arcname=".")

# Read compressed payload
with open(tar_path, "rb") as f:
    payload_bytes = f.read()

os.remove(tar_path)

# AppImage portable self-extractor header
header_script = b'''#!/bin/sh
# OptiCleaner Linux Standalone AppImage Runner
# Generated by OptiCleaner Build Engine

set -e

# Support --appimage-extract
if [ "$1" = "--appimage-extract" ]; then
    DEST_DIR="squashfs-root"
    mkdir -p "$DEST_DIR"
    echo "Extracting OptiCleaner AppImage to $DEST_DIR..."
    SED_LINE=$(grep -a -n "^__ARCHIVE_STARTS_HERE__" "$0" | cut -d: -f1)
    tail -n +$((SED_LINE + 1)) "$0" | tar -xz -C "$DEST_DIR"
    echo "Extracted successfully to $DEST_DIR"
    exit 0
fi

if [ "$1" = "--appimage-version" ] || [ "$1" = "-v" ]; then
    echo "OptiCleaner v3.0.0 (Linux x86_64 AppImage)"
    exit 0
fi

# Create secure temporary extraction directory
TMP_DIR="/tmp/.mount_opticleaner_$$"
mkdir -p "$TMP_DIR"
trap 'rm -rf "$TMP_DIR"' EXIT INT TERM

# Extract payload into temp mount point
SED_LINE=$(grep -a -n "^__ARCHIVE_STARTS_HERE__" "$0" | cut -d: -f1)
tail -n +$((SED_LINE + 1)) "$0" | tar -xz -C "$TMP_DIR"

# Execute AppRun inside isolated environment
cd "$TMP_DIR"
chmod +x "$TMP_DIR/AppRun"
exec "$TMP_DIR/AppRun" "$@"

__ARCHIVE_STARTS_HERE__
'''

appimage_file = os.path.join(linux_dir, "OptiCleaner.AppImage")
with open(appimage_file, "wb") as f:
    f.write(header_script)
    f.write(payload_bytes)

print(f"✓ OptiCleaner.AppImage successfully created: {appimage_file} ({len(payload_bytes)} bytes payload)")
